/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef SWATEQUIPMENT_API
#define SWATEQUIPMENT_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SWATEQUIPMENT_API	FName SWATEQUIPMENT_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(UpdateLight)

#ifndef NAMES_ONLY


// "event"	function whose parameters correspond to	"struct ANVGogglesBase_eventUpdateLight_Parms"	is declared	in "..\SwatEquipment\Classes\Bases\NVGogglesBase.uc"
struct ANVGogglesBase_eventUpdateLight_Parms
{
};
// Class	ANVGogglesBase is declared in "..\SwatEquipment\Classes\Bases\NVGogglesBase.uc"
class SWATEQUIPMENT_API	ANVGogglesBase	: public AProtectiveEquipment
{
public:
    BITFIELD Active:1;
    class UStaticMesh* ActivatedMesh;
    class UStaticMesh* DeactivatedMesh;
    class ADynamicLightEffect* Light;
    FLOAT TransitionStart;
    FLOAT EffectDownTime;
    FLOAT EffectUpTime;
	   DECLARE_FUNCTION(execApplyEnhancement);
	  void	eventUpdateLight()
	  {
		   ProcessEvent(FindFunctionChecked(SWATEQUIPMENT_UpdateLight),NULL);
	  }
	   DECLARE_CLASS(ANVGogglesBase,AProtectiveEquipment,0|CLASS_Config,SwatEquipment)
	   NO_DEFAULT_CONSTRUCTOR(ANVGogglesBase)
};

#endif

AUTOGENERATE_FUNCTION(ANVGogglesBase,-1,execApplyEnhancement);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ANVGogglesBase)
#endif // VERIFY_CLASS_SIZES
