/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef TYRION_API
#define TYRION_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern TYRION_API	FName TYRION_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(OnHearSound)
AUTOGENERATE_NAME(Pawn)
AUTOGENERATE_NAME(ShallowCopyAction)
AUTOGENERATE_NAME(doesParentHaveResource)
AUTOGENERATE_NAME(hasActiveMembers)
AUTOGENERATE_NAME(initAction)
AUTOGENERATE_NAME(instantFail)
AUTOGENERATE_NAME(instantSucceed)
AUTOGENERATE_NAME(multipleActionsCheck)
AUTOGENERATE_NAME(priorityFn)
AUTOGENERATE_NAME(resourceCheck)
AUTOGENERATE_NAME(runAction)
AUTOGENERATE_NAME(selectionHeuristic)

#ifndef NAMES_ONLY

// Constant DEBUGAI_Y is declared in "..\Tyrion\Classes\Engine\AI_Controller.uc"
#define UCONST_DEBUGAI_Y 100
// Constant DEBUGAI_X is declared in "..\Tyrion\Classes\Engine\AI_Controller.uc"
#define UCONST_DEBUGAI_X 20

// "event"	function whose parameters correspond to	"struct AAI_Controller_eventOnHearSound_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Controller.uc"
struct AAI_Controller_eventOnHearSound_Parms
{
	  class AActor* SoundMaker;
	  FVector SoundOrigin;
	  FName SoundCategory;
};
// Constant ONLY_NON_NONE_VALUE is declared in "..\Tyrion\Classes\Engine\AI_Sensor.uc"
#define UCONST_ONLY_NON_NONE_VALUE 2
// Constant ONLY_NONE_VALUE is declared in "..\Tyrion\Classes\Engine\AI_Sensor.uc"
#define UCONST_ONLY_NONE_VALUE 1

// Enum SensorDataType is declared in "..\Tyrion\Classes\Engine\AI_SensorData.uc"
enum SensorDataType
{
	 SDT_FLOAT               =0,
	 SDT_INTEGER             =1,
	 SDT_CATEGORICAL         =2,
	 SDT_OBJECT              =3,
	 SDT_MAX                 =4,
};


// Enum ACT_ErrorCodes is declared in "..\Tyrion\Classes\Engine\ActionBase.uc"
enum ACT_ErrorCodes
{
	 ACT_SUCCESS             =0,
	 ACT_GENERAL_FAILURE     =1,
	 ACT_RESOURCE_INACTIVE   =2,
	 ACT_INTERRUPTED         =3,
	 ACT_CANT_FIND_PATH      =4,
	 ACT_IRREVERSIBLY_OFF_COURSE=5,
	 ACT_TIME_LIMIT_EXCEEDED =6,
	 ACT_INVALID_PARAMETERS  =7,
	 ACT_CANT_REACH_DESTINATION=8,
	 ACT_ALL_RESOURCES_DIED  =9,
	 ACT_REQUIRED_RESOURCE_STOLEN=10,
	 ACT_INSUFFICIENT_RESOURCES_AVAILABLE=11,
	 ACT_NO_COVER_FOUND      =12,
	 ACT_NO_LONGER_THREATENED=13,
	 ACT_WILL_NOT_COMPLY     =14,
	 ACT_NO_WEAPONS_AVAILABLE=15,
	 ACT_NOBODY_HAS_EQUIPMENT=16,
	 ACT_TOO_CLOSE_TO_OFFICERS=17,
	 ACT_DOOR_BLOCKED        =18,
	 ACT_MAX                 =19,
};

// "event"	function whose parameters correspond to	"struct UActionBase_eventinstantFail_Parms"	is declared	in "..\Tyrion\Classes\Engine\ActionBase.uc"
struct UActionBase_eventinstantFail_Parms
{
	  BYTE errorCode;
	  BITFIELD bRemoveGoal;
};
// "event"	function whose parameters correspond to	"struct UActionBase_eventrunAction_Parms"	is declared	in "..\Tyrion\Classes\Engine\ActionBase.uc"
struct UActionBase_eventrunAction_Parms
{
};


// "event"	function whose parameters correspond to	"struct UAI_Action_eventselectionHeuristic_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Action.uc"
struct UAI_Action_eventselectionHeuristic_Parms
{
	  class UAI_Goal* Goal;
	  FLOAT ReturnValue;
};
// "event"	function whose parameters correspond to	"struct UAI_Action_eventinitAction_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Action.uc"
struct UAI_Action_eventinitAction_Parms
{
	  class UAI_Resource* R;
	  class UAI_Goal* Goal;
};
// "event"	function whose parameters correspond to	"struct UAI_Action_eventinstantSucceed_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Action.uc"
struct UAI_Action_eventinstantSucceed_Parms
{
};




// "event"	function whose parameters correspond to	"struct UAI_Goal_eventpriorityFn_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Goal.uc"
struct UAI_Goal_eventpriorityFn_Parms
{
	  INT ReturnValue;
};

// Constant RU_MOUNT is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
#define UCONST_RU_MOUNT 8
// Constant RU_LEGS is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
#define UCONST_RU_LEGS 4
// Constant RU_ARMS is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
#define UCONST_RU_ARMS 2
// Constant RU_HEAD is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
#define UCONST_RU_HEAD 1
// Constant OPTIONAL_RESOURCE_PRIORITY is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
#define UCONST_OPTIONAL_RESOURCE_PRIORITY 20

// "event"	function whose parameters correspond to	"struct UAI_Resource_eventPawn_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Resource.uc"
struct UAI_Resource_eventPawn_Parms
{
	  class APawn* ReturnValue;
};
// "event"	function whose parameters correspond to	"struct UAI_Resource_eventdoesParentHaveResource_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Resource.uc"
struct UAI_Resource_eventdoesParentHaveResource_Parms
{
	  class UAI_Action* parentAction;
	  BITFIELD ReturnValue;
};
// "event"	function whose parameters correspond to	"struct UAI_Resource_eventmultipleActionsCheck_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Resource.uc"
struct UAI_Resource_eventmultipleActionsCheck_Parms
{
	  class UAI_Action* Action;
	  BITFIELD ReturnValue;
};
// "event"	function whose parameters correspond to	"struct UAI_Resource_eventresourceCheck_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Resource.uc"
struct UAI_Resource_eventresourceCheck_Parms
{
	  class UAI_Goal* Goal;
	  class UAI_Action* bestAction;
};
// "event"	function whose parameters correspond to	"struct UAI_Resource_eventShallowCopyAction_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_Resource.uc"
struct UAI_Resource_eventShallowCopyAction_Parms
{
	  class UAI_Action* otherAction;
	  class UAI_Action* ReturnValue;
};

// "event"	function whose parameters correspond to	"struct UAI_SquadResource_eventhasActiveMembers_Parms"	is declared	in "..\Tyrion\Classes\Engine\AI_SquadResource.uc"
struct UAI_SquadResource_eventhasActiveMembers_Parms
{
	  BITFIELD ReturnValue;
};
// Class	AAI_Controller is declared in "..\Tyrion\Classes\Engine\AI_Controller.uc"
class TYRION_API	AAI_Controller	: public AController
{
public:
	  void	eventOnHearSound(class AActor* SoundMaker, FVector SoundOrigin, FName SoundCategory)
	  {
        AAI_Controller_eventOnHearSound_Parms Parms;
		   Parms.SoundMaker=SoundMaker;
		   Parms.SoundOrigin=SoundOrigin;
		   Parms.SoundCategory=SoundCategory;
        ProcessEvent(FindFunctionChecked(TYRION_OnHearSound),&Parms);
	  }
	   DECLARE_CLASS(AAI_Controller,AController,0|CLASS_Config,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(AAI_Controller)
};

// Class	UAI_Sensor is declared in "..\Tyrion\Classes\Engine\AI_Sensor.uc"
class TYRION_API	UAI_Sensor	: public UDeleteableObject
{
public:
    class UAI_SensorAction* sensorAction;
    TArrayNoInit<class UAI_SensorRecipient*> recipients;
    class UAI_SensorData* Value;
    BITFIELD bNotifyOnValueChange:1;
    BITFIELD bNotifyIfResourceInactive:1;
	   DECLARE_CLASS(UAI_Sensor,UDeleteableObject,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_Sensor)
};

// Class	UAI_SensorData is declared in "..\Tyrion\Classes\Engine\AI_SensorData.uc"
class TYRION_API	UAI_SensorData	: public UDeleteableObject
{
public:
    BYTE dataType;
    FLOAT floatData;
    INT integerData;
    class UObject* objectData;
	   DECLARE_CLASS(UAI_SensorData,UDeleteableObject,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_SensorData)
};

// Class	UAI_SensorWithBounds is declared in "..\Tyrion\Classes\Engine\AI_SensorWithBounds.uc"
class TYRION_API	UAI_SensorWithBounds	: public UDeleteableObject
{
public:
    class UAI_Sensor* sensor;
    FLOAT lowerBound;
    FLOAT upperBound;
	   DECLARE_CLASS(UAI_SensorWithBounds,UDeleteableObject,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_SensorWithBounds)
};

// Class	UActionBase is declared in "..\Tyrion\Classes\Engine\ActionBase.uc"
class TYRION_API	UActionBase	: public UTyrion_ActionBase
{
public:
    BITFIELD bIdle:1;
    BITFIELD bCompleted:1;
    BITFIELD bWasTicked:1;
    BITFIELD bDeleted:1;
    BITFIELD bSensorAction:1;
	  void	eventinstantFail(BYTE errorCode, BITFIELD bRemoveGoal)
	  {
        UActionBase_eventinstantFail_Parms Parms;
		   Parms.errorCode=errorCode;
		   Parms.bRemoveGoal=bRemoveGoal;
        ProcessEvent(FindFunctionChecked(TYRION_instantFail),&Parms);
	  }
	  void	eventrunAction()
	  {
		   ProcessEvent(FindFunctionChecked(TYRION_runAction),NULL);
	  }
	   DECLARE_CLASS(UActionBase,UTyrion_ActionBase,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UActionBase)
};

// Class	UAI_RunnableAction is declared in "..\Tyrion\Classes\Engine\AI_RunnableAction.uc"
class TYRION_API	UAI_RunnableAction	: public UActionBase
{
public:
    class UAI_Resource* resource;
	   DECLARE_CLASS(UAI_RunnableAction,UActionBase,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_RunnableAction)
};

// Class	UAI_Action is declared in "..\Tyrion\Classes\Engine\AI_Action.uc"
class TYRION_API	UAI_Action	: public UAI_RunnableAction
{
public:
    class UClass* satisfiesGoal;
    class UAI_Goal* achievingGoal;
    TArrayNoInit<class UAI_Goal*> childGoals;
    FLOAT heuristicValue;
    INT resourceUsage;
    INT waitingForGoalsN;
	  FLOAT	eventselectionHeuristic(class UAI_Goal* Goal)
	  {
        UAI_Action_eventselectionHeuristic_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.Goal=Goal;
        ProcessEvent(FindFunctionChecked(TYRION_selectionHeuristic),&Parms);
		   return Parms.ReturnValue;
	  }
	  void	eventinitAction(class UAI_Resource* R, class UAI_Goal* Goal)
	  {
        UAI_Action_eventinitAction_Parms Parms;
		   Parms.R=R;
		   Parms.Goal=Goal;
        ProcessEvent(FindFunctionChecked(TYRION_initAction),&Parms);
	  }
	  void	eventinstantSucceed()
	  {
		   ProcessEvent(FindFunctionChecked(TYRION_instantSucceed),NULL);
	  }
	   DECLARE_CLASS(UAI_Action,UAI_RunnableAction,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_Action)
};

// Class	UAI_CharacterAction is declared in "..\Tyrion\Classes\Engine\AI_CharacterAction.uc"
class TYRION_API	UAI_CharacterAction	: public UAI_Action
{
public:
    class APawn* Pawn;
    class UAI_MovementResource* movementResourceStorage;
    class UAI_WeaponResource* weaponResourceStorage;
    class UAI_Goal* DummyMovementGoal;
    class UAI_Goal* DummyWeaponGoal;
	   DECLARE_CLASS(UAI_CharacterAction,UAI_Action,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_CharacterAction)
};

// Class	UAI_MovementAction is declared in "..\Tyrion\Classes\Engine\AI_MovementAction.uc"
class TYRION_API	UAI_MovementAction	: public UAI_Action
{
public:
	   DECLARE_CLASS(UAI_MovementAction,UAI_Action,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_MovementAction)
};

// Class	UAI_WeaponAction is declared in "..\Tyrion\Classes\Engine\AI_WeaponAction.uc"
class TYRION_API	UAI_WeaponAction	: public UAI_Action
{
public:
	   DECLARE_CLASS(UAI_WeaponAction,UAI_Action,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_WeaponAction)
};

// Class	UAI_Goal is declared in "..\Tyrion\Classes\Engine\AI_Goal.uc"
class TYRION_API	UAI_Goal	: public UTyrion_GoalBase
{
public:
    BITFIELD bRemoveGoalOfSameType:1;
    BITFIELD bTryOnlyOnce:1;
    INT Priority;
    FStringNoInit goalName;
    class UAI_SensorWithBounds* activationSentinel;
    class UAI_SensorWithBounds* deactivationSentinel;
    class UAI_Action* achievingAction;
    class UAI_Action* parentAction;
    BITFIELD bInactive:1;
    BITFIELD bPermanent:1;
    BITFIELD bDeleted:1;
    BITFIELD bGoalConsidered:1;
    BITFIELD bWakeUpPoster:1;
    BITFIELD bTerminateIfStolen:1;
    BITFIELD bGoalFailed:1;
    BITFIELD bGoalAchieved:1;
    INT ignoreCounter;
    INT matchedN;
    class UAI_Resource* resource;
	   DECLARE_FUNCTION(execcopyParametersFrom);
	  INT	eventpriorityFn()
	  {
        UAI_Goal_eventpriorityFn_Parms Parms;
		   Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(TYRION_priorityFn),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(UAI_Goal,UTyrion_GoalBase,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_Goal)
};

// Class	UAI_CharacterGoal is declared in "..\Tyrion\Classes\Engine\AI_CharacterGoal.uc"
class TYRION_API	UAI_CharacterGoal	: public UAI_Goal
{
public:
	   DECLARE_CLASS(UAI_CharacterGoal,UAI_Goal,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_CharacterGoal)
};

// Class	UAI_Resource is declared in "..\Tyrion\Classes\Engine\AI_Resource.uc"
class TYRION_API	UAI_Resource	: public UTyrion_ResourceBase
{
public:
    TArrayNoInit<class UAI_RunnableAction*> idleActions;
    TArrayNoInit<class UAI_RunnableAction*> runningActions;
    TArrayNoInit<class UAI_RunnableAction*> removedActions;
    class UAI_Action* usedByAction;
    TArrayNoInit<class UAI_Sensor*> sensors;
    TArrayNoInit<class UAI_SensorAction*> sensorActions;
	   DECLARE_FUNCTION(execsetActionParametersInternal);
	   DECLARE_FUNCTION(execfindGoalByName);
	   DECLARE_FUNCTION(execchooseAction);
	   DECLARE_FUNCTION(execdeleteRemovedActions);
	  class APawn*	eventPawn()
	  {
        UAI_Resource_eventPawn_Parms Parms;
		   Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(TYRION_Pawn),&Parms);
		   return Parms.ReturnValue;
	  }
	  BITFIELD	eventdoesParentHaveResource(class UAI_Action* parentAction)
	  {
        UAI_Resource_eventdoesParentHaveResource_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.parentAction=parentAction;
        ProcessEvent(FindFunctionChecked(TYRION_doesParentHaveResource),&Parms);
		   return Parms.ReturnValue;
	  }
	  BITFIELD	eventmultipleActionsCheck(class UAI_Action* Action)
	  {
        UAI_Resource_eventmultipleActionsCheck_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.Action=Action;
        ProcessEvent(FindFunctionChecked(TYRION_multipleActionsCheck),&Parms);
		   return Parms.ReturnValue;
	  }
	  void	eventresourceCheck(class UAI_Goal* Goal, class UAI_Action* bestAction)
	  {
        UAI_Resource_eventresourceCheck_Parms Parms;
		   Parms.Goal=Goal;
		   Parms.bestAction=bestAction;
        ProcessEvent(FindFunctionChecked(TYRION_resourceCheck),&Parms);
	  }
	  class UAI_Action*	eventShallowCopyAction(class UAI_Action* otherAction)
	  {
        UAI_Resource_eventShallowCopyAction_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.otherAction=otherAction;
        ProcessEvent(FindFunctionChecked(TYRION_ShallowCopyAction),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(UAI_Resource,UTyrion_ResourceBase,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_Resource)
};

// Class	UAI_SquadResource is declared in "..\Tyrion\Classes\Engine\AI_SquadResource.uc"
class TYRION_API	UAI_SquadResource	: public UAI_Resource
{
public:
    class ASquadInfo* squad;
	  BITFIELD	eventhasActiveMembers()
	  {
        UAI_SquadResource_eventhasActiveMembers_Parms Parms;
		   Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(TYRION_hasActiveMembers),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(UAI_SquadResource,UAI_Resource,0,Tyrion)
	   NO_DEFAULT_CONSTRUCTOR(UAI_SquadResource)
};

#endif

AUTOGENERATE_FUNCTION(UAI_Goal,-1,execcopyParametersFrom);
AUTOGENERATE_FUNCTION(UAI_Resource,-1,execsetActionParametersInternal);
AUTOGENERATE_FUNCTION(UAI_Resource,-1,execfindGoalByName);
AUTOGENERATE_FUNCTION(UAI_Resource,-1,execchooseAction);
AUTOGENERATE_FUNCTION(UAI_Resource,-1,execdeleteRemovedActions);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UAI_Action)
VERIFY_CLASS_SIZE_NODIE(UAI_CharacterAction)
VERIFY_CLASS_SIZE_NODIE(UAI_CharacterGoal)
VERIFY_CLASS_SIZE_NODIE(AAI_Controller)
VERIFY_CLASS_SIZE_NODIE(UAI_Goal)
VERIFY_CLASS_SIZE_NODIE(UAI_MovementAction)
VERIFY_CLASS_SIZE_NODIE(UAI_Resource)
VERIFY_CLASS_SIZE_NODIE(UAI_RunnableAction)
VERIFY_CLASS_SIZE_NODIE(UAI_Sensor)
VERIFY_CLASS_SIZE_NODIE(UAI_SensorData)
VERIFY_CLASS_SIZE_NODIE(UAI_SensorWithBounds)
VERIFY_CLASS_SIZE_NODIE(UAI_SquadResource)
VERIFY_CLASS_SIZE_NODIE(UAI_WeaponAction)
VERIFY_CLASS_SIZE_NODIE(UActionBase)
#endif // VERIFY_CLASS_SIZES
