/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef RWOSUPPORT_API
#define RWOSUPPORT_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern RWOSUPPORT_API	FName RWOSUPPORT_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(IsDeployed)
AUTOGENERATE_NAME(RemoveProjectors)

#ifndef NAMES_ONLY


// "event"	function whose parameters correspond to	"struct AReactiveWorldObject_eventRemoveProjectors_Parms"	is declared	in "..\RWOSupport\Classes\ReactiveWorldObject.uc"
struct AReactiveWorldObject_eventRemoveProjectors_Parms
{
};
// Enum WhenDone is declared in "..\RWOSupport\Classes\ReactiveAnimatedMesh.uc"
enum WhenDone
{
	 WhenDone_Idle           =0,
	 WhenDone_LoopLastAnimationSet=1,
	 WhenDone_RepeatFromStart=2,
	 WhenDone_Freeze         =3,
	 WhenDone_Destroy        =4,
	 WhenDone_MAX            =5,
};
// Struct FAnimatedMeshAttachment	is declared	in "..\RWOSupport\Classes\ReactiveAnimatedMesh.uc"
struct RWOSUPPORT_API FAnimatedMeshAttachment
{
    class UStaticMesh* Attachment;
    FName Socket;
};

// Struct FPreCreatedAttachment	is declared	in "..\RWOSupport\Classes\ReactiveAnimatedMesh.uc"
struct RWOSUPPORT_API FPreCreatedAttachment
{
    FName Label;
    FName Socket;
};




// "event"	function whose parameters correspond to	"struct ADeployedTacticalAid_eventIsDeployed_Parms"	is declared	in "..\RWOSupport\Classes\DeployedTacticalAid.uc"
struct ADeployedTacticalAid_eventIsDeployed_Parms
{
	  BITFIELD ReturnValue;
};


// Struct FScriptedAnimation	is declared	in "..\RWOSupport\Classes\ScriptedAnimationSet.uc"
struct RWOSUPPORT_API FScriptedAnimation
{
    INT Chance;
    FName Animation;
};


// Class	AReactiveWorldObject is declared in "..\RWOSupport\Classes\ReactiveWorldObject.uc"
class RWOSUPPORT_API	AReactiveWorldObject	: public AHavokActor
{
public:
    TArrayNoInit<class UHandler_Damaged*> DamagedHandlers;
    TArrayNoInit<class UHandler_Bumped*> BumpedHandlers;
    TArrayNoInit<class UHandler_Used*> UsedHandlers;
    TArrayNoInit<class UHandler_Triggered*> TriggeredHandlers;
    TArrayNoInit<class UHandler_GrenadeDetonated*> GrenadeDetonatedHandlers;
    TArrayNoInit<class UHandler_TimerExpired*> TimerExpiredHandlers;
    BITFIELD UsableNow:1;
    BITFIELD TriggerableNow:1;
    BITFIELD IgnoreZeroDamage:1;
    BITFIELD ShouldReactToTriggeredOnPostBeginPlayInMP:1;
    BITFIELD IsConseptuallyBroken:1;
    BITFIELD bHighDetailOnly:1;
    BITFIELD bClientOnly:1;
    FLOAT hkMass;
    BITFIELD hkStabilizedInertia:1;
    FLOAT hkFriction;
    FLOAT hkRestitution;
    FLOAT hkLinearDamping;
    FLOAT hkAngularDamping;
    BITFIELD hkActive:1;
    BITFIELD hkKeyframed:1;
    FVector hkLinearVel;
    FVector hkAngularVel;
    FLOAT hkForceUprightStrength;
    FLOAT hkForceUprightDamping;
    BYTE hkForceUpright;
    INT hkCollisionLayer;
    INT hkCollisionSystemGroup;
    INT hkCollisionSubpartID;
    INT hkCollisionSubpartIgnoreID;
    BITFIELD useIntrusionDrivenUpdates:1;
    FName SkeletonPhysicsFile;
    FLOAT hkJointFriction;
    BITFIELD bShouldDestroySelf:1;
	   DECLARE_FUNCTION(execRemoveProjectors);
	   DECLARE_FUNCTION(execDestroyRWO);
	  void	eventRemoveProjectors()
	  {
		   ProcessEvent(FindFunctionChecked(RWOSUPPORT_RemoveProjectors),NULL);
	  }
	   DECLARE_CLASS(AReactiveWorldObject,AHavokActor,0|CLASS_Config,RWOSupport)
	   NO_DEFAULT_CONSTRUCTOR(AReactiveWorldObject)
};

// Class	AReactiveAnimatedMesh is declared in "..\RWOSupport\Classes\ReactiveAnimatedMesh.uc"
class RWOSUPPORT_API	AReactiveAnimatedMesh	: public AReactiveWorldObject
{
public:
    TArrayNoInit<FString> ExtraAnimationSets;
    class UScriptedAnimationSet* Idle;
    TArrayNoInit<class UScriptedAnimationSet*> ScriptedSequence;
    BYTE WhenDoneDo;
    TArrayNoInit<FAnimatedMeshAttachment> AnimatedMeshAttachments;
    TArrayNoInit<class AAnimatedMeshAttachmentModel*> AnimatedMeshAttachmentModels;
    TArrayNoInit<FPreCreatedAttachment> PreCreatedAttachments;
	   DECLARE_FUNCTION(execUnlinkScriptedAnimationSet);
	   DECLARE_CLASS(AReactiveAnimatedMesh,AReactiveWorldObject,0|CLASS_Config,RWOSupport)
	   NO_DEFAULT_CONSTRUCTOR(AReactiveAnimatedMesh)
};

// Class	AReactiveStaticMesh is declared in "..\RWOSupport\Classes\ReactiveStaticMesh.uc"
class RWOSUPPORT_API	AReactiveStaticMesh	: public AReactiveWorldObject
{
public:
	   DECLARE_CLASS(AReactiveStaticMesh,AReactiveWorldObject,0|CLASS_Config,RWOSupport)
	   NO_DEFAULT_CONSTRUCTOR(AReactiveStaticMesh)
};

// Class	ADeployedTacticalAid is declared in "..\RWOSupport\Classes\DeployedTacticalAid.uc"
class RWOSUPPORT_API	ADeployedTacticalAid	: public AReactiveStaticMesh
{
public:
	   DECLARE_FUNCTION(execIsDeployed);
	  BITFIELD	eventIsDeployed()
	  {
        ADeployedTacticalAid_eventIsDeployed_Parms Parms;
		   Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(RWOSUPPORT_IsDeployed),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(ADeployedTacticalAid,AReactiveStaticMesh,0|CLASS_Config,RWOSupport)
    // To ensure when deployed on a door the object is lit by lights
    // in neighboring zones (make the object bigger than it actually
    // is for lighting purposes) 
    void PredictedBoxAdjustmentHook(FBox& PredictedBox);
};

// Class	UHandler is declared in "..\RWOSupport\Classes\Handler.uc"
class RWOSUPPORT_API	UHandler	: public UObject
{
public:
    TArrayNoInit<class UReaction*> Reactions;
	   DECLARE_CLASS(UHandler,UObject,0,RWOSupport)
    void CleanupRefs();
    void DetachReactions();
    void CheckForErrors(const TCHAR* RWOName, const TCHAR* HandlersName);
};

// Class	UReaction is declared in "..\RWOSupport\Classes\Reaction.uc"
class RWOSUPPORT_API	UReaction	: public UObject
{
public:
    BITFIELD OnceOnly:1;
    BITFIELD Done:1;
    FName Event;
	   DECLARE_CLASS(UReaction,UObject,0,RWOSupport)
	   NO_DEFAULT_CONSTRUCTOR(UReaction)
};

// Class	UScriptedAnimationSet is declared in "..\RWOSupport\Classes\ScriptedAnimationSet.uc"
class RWOSUPPORT_API	UScriptedAnimationSet	: public UObject
{
public:
    TArrayNoInit<FScriptedAnimation> ScriptedAnimations;
    FRange LoopCount;
    INT TotalChance;
	   DECLARE_CLASS(UScriptedAnimationSet,UObject,0,RWOSupport)
	   NO_DEFAULT_CONSTRUCTOR(UScriptedAnimationSet)
};

#endif

AUTOGENERATE_FUNCTION(ADeployedTacticalAid,-1,execIsDeployed);
AUTOGENERATE_FUNCTION(AReactiveAnimatedMesh,-1,execUnlinkScriptedAnimationSet);
AUTOGENERATE_FUNCTION(AReactiveWorldObject,-1,execRemoveProjectors);
AUTOGENERATE_FUNCTION(AReactiveWorldObject,-1,execDestroyRWO);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ADeployedTacticalAid)
VERIFY_CLASS_SIZE_NODIE(UHandler)
VERIFY_CLASS_SIZE_NODIE(UReaction)
VERIFY_CLASS_SIZE_NODIE(AReactiveAnimatedMesh)
VERIFY_CLASS_SIZE_NODIE(AReactiveStaticMesh)
VERIFY_CLASS_SIZE_NODIE(AReactiveWorldObject)
VERIFY_CLASS_SIZE_NODIE(UScriptedAnimationSet)
#endif // VERIFY_CLASS_SIZES
