/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef SWATAIAWARENESS_API
#define SWATAIAWARENESS_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SWATAIAWARENESS_API	FName SWATAIAWARENESS_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(GetKnownLocationOfPawn)
AUTOGENERATE_NAME(IsOtherActorAThreat)
AUTOGENERATE_NAME(RegisterHearingNotification)
AUTOGENERATE_NAME(RegisterVisionNotification)
AUTOGENERATE_NAME(UnregisterHearingNotification)
AUTOGENERATE_NAME(UnregisterVisionNotification)

#ifndef NAMES_ONLY


// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventGetKnownLocationOfPawn_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_GetKnownLocationOfPawn_Parms
{
	  class APawn* otherPawn;
	  FVector Location;
	  BITFIELD ReturnValue;
};
// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventIsOtherActorAThreat_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_IsOtherActorAThreat_Parms
{
	  class AActor* otherActor;
	  BITFIELD ReturnValue;
};
// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventUnregisterHearingNotification_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_UnregisterHearingNotification_Parms
{
	  class IIHearingNotification* Registrant;
};
// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventRegisterHearingNotification_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_RegisterHearingNotification_Parms
{
	  class IIHearingNotification* Registrant;
};
// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventUnregisterVisionNotification_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_UnregisterVisionNotification_Parms
{
	  class IIVisionNotification* Registrant;
};
// "event"	function whose parameters correspond to	"struct IIAwarenessOuter_eventRegisterVisionNotification_Parms"	is declared	in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
struct IIAwarenessOuter_RegisterVisionNotification_Parms
{
	  class IIVisionNotification* Registrant;
};
// Class	IIAwarenessOuter is declared in "..\SwatAIAwareness\Classes\IAwarenessOuter.uc"
class SWATAIAWARENESS_API	IIAwarenessOuter	: public UObject
{
public:
	  BITFIELD GetKnownLocationOfPawn(class APawn* otherPawn, FVector& Location)
	  {
        IIAwarenessOuter_GetKnownLocationOfPawn_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.otherPawn=otherPawn;
		   Parms.Location=Location;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_GetKnownLocationOfPawn),&Parms);
		   Location=Parms.Location;
		   return Parms.ReturnValue;
	  }
	  BITFIELD IsOtherActorAThreat(class AActor* otherActor)
	  {
        IIAwarenessOuter_IsOtherActorAThreat_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.otherActor=otherActor;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_IsOtherActorAThreat),&Parms);
		   return Parms.ReturnValue;
	  }
	  void UnregisterHearingNotification(class IIHearingNotification* Registrant)
	  {
        IIAwarenessOuter_UnregisterHearingNotification_Parms Parms;
		   Parms.Registrant=Registrant;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_UnregisterHearingNotification),&Parms);
	  }
	  void RegisterHearingNotification(class IIHearingNotification* Registrant)
	  {
        IIAwarenessOuter_RegisterHearingNotification_Parms Parms;
		   Parms.Registrant=Registrant;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_RegisterHearingNotification),&Parms);
	  }
	  void UnregisterVisionNotification(class IIVisionNotification* Registrant)
	  {
        IIAwarenessOuter_UnregisterVisionNotification_Parms Parms;
		   Parms.Registrant=Registrant;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_UnregisterVisionNotification),&Parms);
	  }
	  void RegisterVisionNotification(class IIVisionNotification* Registrant)
	  {
        IIAwarenessOuter_RegisterVisionNotification_Parms Parms;
		   Parms.Registrant=Registrant;
        ProcessFunction(FindFunctionChecked(SWATAIAWARENESS_RegisterVisionNotification),&Parms);
	  }
	   DECLARE_CLASS(IIAwarenessOuter,UObject,0|CLASS_Interface,SwatAIAwareness)
	   NO_DEFAULT_CONSTRUCTOR(IIAwarenessOuter)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(IIAwarenessOuter)
#endif // VERIFY_CLASS_SIZES
