/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef SWATGUI_API
#define SWATGUI_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SWATGUI_API	FName SWATGUI_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(OnURLFailed)

#ifndef NAMES_ONLY




// "event"	function whose parameters correspond to	"struct USwatPatchingPopup_eventOnURLFailed_Parms"	is declared	in "..\SwatGui\Classes\SwatPatchingPopup.uc"
struct USwatPatchingPopup_eventOnURLFailed_Parms
{
	  FString Error;
};

// Class	USwatGuiPopup is declared in "..\SwatGui\Classes\SwatGUIPopup.uc"
class SWATGUI_API	USwatGuiPopup	: public UGUIPage
{
public:
    class USwatGUIConfig* GC;
    class UGUIButton* MyOKButton;
    class UGUIButton* MyCancelButton;
    FStringNoInit Passback;
    FGUIListElem ReturnElem;
	   DECLARE_CLASS(USwatGuiPopup,UGUIPage,0|CLASS_Config,SwatGui)
	   NO_DEFAULT_CONSTRUCTOR(USwatGuiPopup)
};

// Class	USwatGamespyProfilePopup is declared in "..\SwatGui\Classes\SwatGamespyProfilePopup.uc"
class SWATGUI_API	USwatGamespyProfilePopup	: public USwatGuiPopup
{
public:
    class UGUIEditBox* Username;
    class UGUIEditBox* Email;
    class UGUIEditBox* Password;
    class UGUICheckBoxButton* SavePassword;
    class UGUIButton* LoginCreate;
    class UGUIButton* Done;
    class UGUILabel* Info;
    FStringNoInit DoneText;
    FStringNoInit CancelText;
    FStringNoInit WaitText;
    FStringNoInit ResultBadEmail;
    FStringNoInit ResultBadLogin;
    FStringNoInit ResultBadPassword;
    FStringNoInit ResultCreateOk;
    FStringNoInit ResultCreateBadPassword;
    FStringNoInit ResultLoginOk;
    FStringNoInit ResultLoginAfterCreateOk;
    FStringNoInit ResultUnknown;
    FStringNoInit LoggingInText;
    FStringNoInit ProfileCreated;
    FStringNoInit ProfileCreating;
    FStringNoInit ProfileConnected;
    FStringNoInit ProfileNotConnected;
    FStringNoInit ProfileDetailsButNotConnected;
    FStringNoInit ValidateBadUsername;
    FStringNoInit ValidateBadUsernameFirstChar;
    FStringNoInit ValidateBadPassword;
    FStringNoInit ValidateBadEmail;
    class USwatGameSpyManager* SGSM;
    BITFIELD bCreating:1;
    BITFIELD bOpen:1;
    FStringNoInit TimerOp;
	   DECLARE_FUNCTION(execValidate);
	   DECLARE_CLASS(USwatGamespyProfilePopup,USwatGuiPopup,0|CLASS_Config,SwatGui)
	   NO_DEFAULT_CONSTRUCTOR(USwatGamespyProfilePopup)
};

// Class	USwatPatchingPopup is declared in "..\SwatGui\Classes\SwatPatchingPopup.uc"
class SWATGUI_API	USwatPatchingPopup	: public USwatGuiPopup
{
public:
    class UGUIButton* Cancel;
    class UGUIButton* Yes;
    class UGUIButton* No;
    class UGUIButton* Ok;
    class UGUILabel* Info;
    FStringNoInit PatchAvailableText;
    FStringNoInit PatchAvailableText2;
    FStringNoInit NoPatchAvailableText;
    FStringNoInit LaunchFailedText;
    FStringNoInit CheckingText;
    FStringNoInit LaunchURL;
    class USwatGameSpyManager* SGSM;
	   DECLARE_FUNCTION(execOnYes);
	  void	eventOnURLFailed(const FString& Error)
	  {
        USwatPatchingPopup_eventOnURLFailed_Parms Parms;
		   Parms.Error=Error;
        ProcessEvent(FindFunctionChecked(SWATGUI_OnURLFailed),&Parms);
	  }
	   DECLARE_CLASS(USwatPatchingPopup,USwatGuiPopup,0|CLASS_Config,SwatGui)
	   NO_DEFAULT_CONSTRUCTOR(USwatPatchingPopup)
};

// Class	UNativeBootstrap is declared in "..\SwatGui\Classes\NativeBootstrap.uc"
class SWATGUI_API	UNativeBootstrap	: public UObject
{
public:
	   DECLARE_CLASS(UNativeBootstrap,UObject,0,SwatGui)
	   NO_DEFAULT_CONSTRUCTOR(UNativeBootstrap)
};

#endif

AUTOGENERATE_FUNCTION(USwatGamespyProfilePopup,-1,execValidate);
AUTOGENERATE_FUNCTION(USwatPatchingPopup,-1,execOnYes);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UNativeBootstrap)
VERIFY_CLASS_SIZE_NODIE(USwatGamespyProfilePopup)
VERIFY_CLASS_SIZE_NODIE(USwatGuiPopup)
VERIFY_CLASS_SIZE_NODIE(USwatPatchingPopup)
#endif // VERIFY_CLASS_SIZES
