/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API	FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)
AUTOGENERATE_NAME(CreateMaterial)

#ifndef NAMES_ONLY



// "event"	function whose parameters correspond to	"struct UBrushBuilder_eventBuild_Parms"	is declared	in "..\Editor\Classes\BrushBuilder.uc"
struct UBrushBuilder_eventBuild_Parms
{
	  BITFIELD ReturnValue;
};
// Constant RF_Standalone is declared in "..\Editor\Classes\MaterialFactory.uc"
#define UCONST_RF_Standalone 0x00080000

// "event"	function whose parameters correspond to	"struct UMaterialFactory_eventCreateMaterial_Parms"	is declared	in "..\Editor\Classes\MaterialFactory.uc"
struct UMaterialFactory_eventCreateMaterial_Parms
{
	  class UObject* InOuter;
	  FString InPackage;
	  FString InGroup;
	  FString InName;
	  class UMaterial* ReturnValue;
};
// Class	UAnimNotifyProps is declared in "..\Editor\Classes\AnimNotifyProps.uc"
class EDITOR_API	UAnimNotifyProps	: public UObject
{
public:
    class UAnimNotify* Notify;
	   DECLARE_CLASS(UAnimNotifyProps,UObject,0,Editor)
	   NO_DEFAULT_CONSTRUCTOR(UAnimNotifyProps)
};

// Class	UBrushBuilder is declared in "..\Editor\Classes\BrushBuilder.uc"
class EDITOR_API	UBrushBuilder	: public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    TArrayNoInit<FVector> Vertices;
    TArrayNoInit<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1;
	   DECLARE_FUNCTION(execPolyEnd);
	   DECLARE_FUNCTION(execPolyi);
	   DECLARE_FUNCTION(execPolyBegin);
	   DECLARE_FUNCTION(execPoly4i);
	   DECLARE_FUNCTION(execPoly3i);
	   DECLARE_FUNCTION(execVertex3f);
	   DECLARE_FUNCTION(execVertexv);
	   DECLARE_FUNCTION(execBadParameters);
	   DECLARE_FUNCTION(execGetPolyCount);
	   DECLARE_FUNCTION(execGetVertex);
	   DECLARE_FUNCTION(execGetVertexCount);
	   DECLARE_FUNCTION(execEndBrush);
	   DECLARE_FUNCTION(execBeginBrush);
	  BITFIELD	eventBuild()
	  {
        UBrushBuilder_eventBuild_Parms Parms;
		   Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(UBrushBuilder,UObject,0,Editor)
	   NO_DEFAULT_CONSTRUCTOR(UBrushBuilder)
};

// Class	UMaterialFactory is declared in "..\Editor\Classes\MaterialFactory.uc"
class EDITOR_API	UMaterialFactory	: public UObject
{
public:
    FStringNoInit Description;
	   DECLARE_FUNCTION(execConsoleCommand);
	  class UMaterial*	eventCreateMaterial(class UObject* InOuter, const FString& InPackage, const FString& InGroup, const FString& InName)
	  {
        UMaterialFactory_eventCreateMaterial_Parms Parms;
		   Parms.ReturnValue=0;
		   Parms.InOuter=InOuter;
		   Parms.InPackage=InPackage;
		   Parms.InGroup=InGroup;
		   Parms.InName=InName;
        ProcessEvent(FindFunctionChecked(EDITOR_CreateMaterial),&Parms);
		   return Parms.ReturnValue;
	  }
	   DECLARE_CLASS(UMaterialFactory,UObject,0,Editor)
	   NO_DEFAULT_CONSTRUCTOR(UMaterialFactory)
};

#endif

AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);
AUTOGENERATE_FUNCTION(UMaterialFactory,-1,execConsoleCommand);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UAnimNotifyProps)
VERIFY_CLASS_SIZE_NODIE(UBrushBuilder)
VERIFY_CLASS_SIZE_NODIE(UMaterialFactory)
#endif // VERIFY_CLASS_SIZES
